platform :ios, '9.0'

target 'Stevens Social' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stevens Social
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'ChameleonFramework'
  pod "YouTube-Player-iOS-Helper"
  target 'Stevens SocialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Stevens SocialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end

            
